=== openstreetmap/svn-archive/applications/utils/osmolt/source/grammar.dtd
<!ELEMENT MapFeatures (entry*)>

<!ELEMENT entry (filter,titel,description)>

<!ELEMENT filter (restriction|filter)+>
<!ELEMENT titel (#PCDATA|valueof)* >
<!ELEMENT description (#PCDATA|valueof|br)* >

<!ELEMENT restriction EMPTY>
<!ELEMENT valueof EMPTY>
<!ELEMENT br EMPTY>


<!ATTLIST entry
   osmKey		CDATA    #REQUIRED
   osmValue		CDATA    #REQUIRED
   filename		CDATA    #REQUIRED
   image		CDATA    #REQUIRED
   name			CDATA    #REQUIRED
   imagesize	CDATA    #REQUIRED
   imageoffset	CDATA    #REQUIRED
>

<!ATTLIST filter
   name			CDATA    #REQUIRED
   logical		CDATA    #REQUIRED
   negation		CDATA	 #IMPLIED
>
<!ATTLIST restriction
   osmKey		CDATA    #REQUIRED
   osmValue		CDATA    #REQUIRED
   negation		CDATA	 #IMPLIED
>

<!ATTLIST valueof
   osmKey		CDATA    #REQUIRED
>

=== openstreetmap/svn-archive/applications/utils/osmolt/source/mapFeatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MapFeatures SYSTEM "grammar.dtd">
<MapFeatures>
	<entry osmKey="leisure" osmValue="playground" filename="playground.txt" name="Spielplatz" image="playground.png" imagesize="20,20" imageoffset="-8,-8">
		<filter logical="and">
	    	<restriction osmKey="leisure" osmValue="playground"/>
	    	<filter logical="or" negation="true">
	    		<restriction osmKey="name" osmValue="Waldspielplatz"/>
	    		<restriction osmKey="operator" osmValue="Stadtwedel"/>
			</filter>
		</filter>
		<titel>
			Spielplatz
		</titel>
		<description>
			<valueof osmKey="name"/>
			blablub
		</description>
	</entry>
</MapFeatures>
